### ISSUE TITLE
Django 2.2 support 

### ISSUE THREAD

**Issue by devbis** [mattiaslinnap/django-partial-index#17]
When I use django 2.2 with django-partial-index I see the exception:

```
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 315, in __new__
    new_class._prepare()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 367, in _prepare
    index.set_name_with_model(cls)
  File "/usr/local/lib/python3.7/site-packages/partial_index/index.py", line 146, in set_name_with_model
    '%s_%s' % (self._hash_generator(*hash_data), self.suffix),
AttributeError: 'PartialIndex' object has no attribute '_hash_generator'
```

`_hash_generator` method in Django 2.2 was moved to a function:

`from django.db.backends.utils import names_digest`

**Comment by levic** [comment]
Django 2.2 supports [partial indexes natively](https://docs.djangoproject.com/en/2.2/ref/models/indexes/#django.db.models.Index.condition) and [uniqueness constraints on partial indexes](https://docs.djangoproject.com/en/2.2/ref/models/constraints/#uniqueconstraint)

Wouldn't it be easier to just change to use that?

**Comment by brianwawok** [comment]
At a min should throw that we don't support Django 2.2 with this package?

**Comment by levic** [comment]
After further investigation (see my comment in #18) core django [doesn't validate partial unique constraints](https://github.com/django/django/blob/5d1cf9c4424e976af71fd079165d86d2bcc13fa9/django/db/models/base.py#L1018) in `Model.full_clean()` so unless django core fixes this `django-partial-index` still has a place

**Comment by mattiaslinnap** [comment]
Thanks for the report!

Yes, with Django 2.2 now having partial index support, this package is no longer needed. It was built at a time when this was not available in core.

However, I plan on maintaining it for all the projects out there that are still on older versions of Django. Fixing Django 2.2 support will come soon as well - I got stuck upgrading my own projects to 2.2 because of this same issue.

**Comment by anaveld** [comment]
I have question for current situation - is it possible to switch from this package to native django Index in django 2.2 without recreating the index?

**Comment by mattiaslinnap** [comment]
Hi @anaveld,

It is not just yet - but I will add Django 2.2 support Soon™ (hopefully next week) now. This will mean that:

* django-partial-index projects can be upgraded to Django 2.2 and keep the existing indexes,
* These indexes can be removed, and identical ones added with Django migrations.

The old partial index will be dropped and a new partial index will be created, but both of these should happen in a single atomic transaction.

**Comment by anaveld** [comment]
Hello @mattiaslinnap,

That's good to hear. To be honest I'm counting on this update to happen soon, since we're planning upgrade of big project to django 2.2 - if you need any help with coding this out faster just let me know and I can help. :)

**Comment by nicolasVaye** [comment]
I confirm that django 2.2.2 doesn't validate UniqueConstraint   but   django-partial-index **DOES** so unless django core fixes this,  **django-partial-index still has a place even in 2.2**

Could we get a release with django 2.2 support please ?

**Comment by mattiaslinnap** [comment]
Hi @devbis @levic @brianwawok @anaveld @nicolasVaye  - version 0.6.0 with Django 2.2 support now released!

The update itself was embarrassingly easy, it took much more time to fix the tests to run on new Travis CI environments.

TIL that Django's version does not actually support unique partial constraints - that's the main use case for partial indexes for me. All the "unique if not deleted", "unique per room", and so on constraints.

**Comment by anaveld** [comment]
@mattiaslinnap Thank you very much! I've already tried it but it disallows be to use the same index because I had it on <foreign_key_name>_id and now it throws `(models.E012) 'indexes' refers to the nonexistent field 'user_id'.` Any ideas? :)

**Comment by mattiaslinnap** [comment]
Hi @anaveld , could you please tell me which Django version you started the upgrade from, and share the model class definition please?

**Comment by anaveld** [comment]
Thanks @mattiaslinnap . I've done update from 1.11 do 2.2. The model has ForeignKey to User model called `user` and we had index like `fields=['user_id', 'view_in_dashboard', 'create_ts', 'delete_ts'],` Changing index to just user makes django-migrations recreate the index. I guess something has changed inside django which makes _id notation obsolete.

**Comment by simkimsia** [comment]
I have been using django partial index with django 2.2 so far so good

And my main and only usage of this package is so that I can add unique partial index to my model

So should this issue b  closed?

**Comment by sjamaan** [comment]
I think the ticket can be closed, we're using it in a few big projects here, and it's working fine.
