### ISSUE TITLE
User-friendly error messages for ModelForms

### ISSUE THREAD

**Issue by mattiaslinnap** [mattiaslinnap/django-partial-index#4]
Currently when you save data that violates a unique=True PartialIndex, the database backend will raise an IntegrityError. This can show up as a "500 Server Error" page.

If a partial unique constraint exists on a model, then ModelForms derived from it should automatically get some sort of validation with nice error messages.

**Comment by Bartvds** [comment]
This would be very helpful as currently the partial unique index isn't very usable with data that is edited through the admin. 

If you have partial unique for object that are manged with inline admin's the browser back button won't restore the extra inline forms for new objects and you'd loose your data-entry work.

**Comment by mattiaslinnap** [comment]
Now part of the v0.5 release.
