### ISSUE TITLE
Use Django's Q-expressions instead of text for the where-condition of the partial index.

### ISSUE THREAD

**Issue by mattiaslinnap** [mattiaslinnap/django-partial-index#8]
This would have three main advantages:

* More "djangonic" than writing raw SQL,
* No need to provide separate conditions for PostgreSQL and SQLite for boolean conditions,
* May be easier to parse for form validation.

**Comment by WhyNotHugo** [comment]
Came here to propose exactly that!
I'll try diving into the code and see if I can draft something up -- no promises though. Nice to see it in the backlog though! 😉

**Comment by mattiaslinnap** [comment]
Now released in v0.5

**Comment by WhyNotHugo** [comment]
Thanks!

--
Hugo Osvaldo Barrera
